import { useState } from 'react';

const services = [
  ['01', '✦', 'Tooth extraction', 'Safe, gentle removal of impacted or decayed teeth.'],
  ['02', '◒', 'Teeth cleaning', 'Preventive care to remove plaque and protect gums.'],
  ['03', '◡', 'Orthodontics', 'Braces and aligners for a beautifully balanced smile.'],
  ['04', '✧', 'Tooth filling', 'Natural-looking restorations for strength and comfort.'],
  ['05', '☼', 'Teeth whitening', 'Cosmetic bleaching for a brighter, more confident smile.'],
  ['06', '◌', 'Complete dentures', 'Custom replacements to restore confidence and function.'],
];
const testimonials = [
  ['The doctors are extremely kind and attentive. My braces treatment is progressing really well. 5/5.', 'Manisha M', 'ORTHODONTIC PATIENT'],
  ['I got my teeth cleaned and whitened here, and the results were amazing. The staff is so humble and professional.', 'Mr. Arun Kumar', 'GENERAL DENTISTRY PATIENT'],
  ['The entire process from consultation to regular follow ups has been so smooth. Really grateful for their care.', 'Mrs. Revathi S.', 'PARENT & PATIENT'],
];
const faqs = [
  ['Can medication completely relieve tooth pain?', 'Medication may provide short-term relief, but lasting relief requires a dentist to identify and treat the root cause.'],
  ['Does teeth scaling damage enamel?', 'No. Scaling safely removes plaque and tartar. Some temporary sensitivity can occur as gums heal.'],
  ['What is the best age to get braces?', 'Braces are often most effective between ages 12 and 14, though earlier treatment may help in some cases.'],
  ['How often should I see a dentist?', 'We recommend a regular check-up every six months for preventive care and professional cleaning.'],
];
const Brand = () => <a className="brand" href="#home"><span className="brand-mark">✦</span><span>Sakthi <b>Dental</b><small>CLINIC</small></span></a>;

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false), [appointmentOpen, setAppointmentOpen] = useState(false), [quote, setQuote] = useState(0), [formMessage, setFormMessage] = useState('');
  const nav = ['About us', 'Treatments', 'Facilities', 'FAQs', 'Contact'];
  const anchors = ['about', 'treatments', 'facilities', 'faq', 'contact'];
  const submit = event => { event.preventDefault(); const form = event.currentTarget; if (!form.checkValidity()) { setFormMessage('Please complete your name, a valid email, and phone number.'); form.reportValidity(); return; } setFormMessage('Thank you - your message is ready to be sent to our team.'); form.reset(); };
  return <>
    <div className="topline"><div className="container"><span>Open daily, 9 AM - 7 PM</span><a href="tel:+919862890897">+91 98628 90897</a></div></div>
    <header className="header"><div className={`container nav ${menuOpen ? 'open' : ''}`}><Brand /><button className="menu" aria-label="Open navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>☰</button><nav>{nav.map((item, i) => <a onClick={() => setMenuOpen(false)} href={`#${anchors[i]}`} key={item}>{item}</a>)}</nav><button className="button small" onClick={() => setAppointmentOpen(true)}>Fix an appointment <span>→</span></button></div></header>
    <main>
      <section id="home" className="hero"><div className="container hero-grid"><div><p className="eyebrow">WELCOME TO SAKTHI DENTAL CLINIC</p><h1>Care that makes<br />you <em>smile.</em></h1><p className="intro">Specialized dental care for women, children & families. Experience expert-led treatment in a space designed around your comfort.</p><div className="hero-actions"><button className="button" onClick={() => setAppointmentOpen(true)}>Fix an appointment <span>→</span></button><a href="#treatments" className="text-link">Explore treatments <span>↗</span></a></div><div className="trust"><div><strong>20+</strong><span>years of trusted care</span></div><div><strong>9 AM - 7 PM</strong><span>available every day</span></div></div></div><div className="hero-art"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-card"><img src="https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1100&q=85" alt="Dentist reassuring a young patient"/><div className="image-label"><span className="star">✦</span><span>Gentle care for<br/><b>every generation</b></span></div></div><div className="float-note"><span>♡</span><p>“You are always<br/><b>in safe hands.”</b></p></div></div></div></section>
      <section className="assurance"><div className="container"><span className="spark">✦</span><p>We are ready to help, <i>anytime.</i></p><span className="assurance-line"/><span className="spark">✦</span></div></section>
      <section id="about" className="section why"><div className="container two-col"><div><p className="eyebrow">WHY SAKTHI DENTAL CLINIC</p><h2>More than treatment.<br/>A better dental experience.</h2><p className="body-copy">We pair clinical excellence with an atmosphere of ease, so every person who walks in feels heard, cared for, and confident about their smile.</p><a href="#doctor" className="text-link">Meet our doctor <span>↗</span></a></div><div className="feature-list">{[['⌂','All-in-one care','From general dentistry to specialized treatments, everything under one roof.'],['✦','Experienced doctors','Professionally trained dentists committed to personalized patient care.'],['♡','Patient-first approach','Comfort, safety and transparency guide every treatment we offer.'],['⌁','Technology-driven','Modern tools and equipment bring precision and peace of mind.']].map(([icon,title,text]) => <article key={title}><span className="feature-icon">{icon}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
      <section id="treatments" className="section treatments"><div className="container"><div className="section-head"><div><p className="eyebrow">OUR CORE TREATMENTS</p><h2>Explore our services.</h2></div><a href="#treatment-list" className="text-link">View all treatments <span>↗</span></a></div><div className="treatment-grid">{services.map(([number,icon,title,text]) => <article key={title}><span>{number}</span><div className="treatment-icon">{icon}</div><h3>{title}</h3><p>{text}</p><a href="#treatment-list" aria-label={`Learn about ${title}`}>↗</a></article>)}</div></div></section>
      <section id="doctor" className="section doctor"><div className="container doctor-grid"><div className="doctor-image"><img src="https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=900&q=85" alt="Doctor in a white coat"/><span>20+<small>years of experience</small></span></div><div><p className="eyebrow">GET TO KNOW DR. ANUPRIYA</p><h2>Your trusted partner in dental care.</h2><p className="body-copy">Bringing over 20 years of expertise to Hosur, Dr. Anupriya founded Sakthi Dental Clinic with a vision to make high-quality, compassionate dental care accessible to all.</p><p className="body-copy">Her team blends advanced technology with a warm, patient-friendly approach - from routine check-ups to specialized procedures.</p><div className="doctor-sign">Dr. Anupriya <small>FOUNDER, SAKTHI DENTAL CLINIC</small></div></div></div></section>
      <section id="facilities" className="section facilities"><div className="container"><p className="eyebrow">CLINIC FACILITIES</p><h2>Thoughtful in every detail.</h2><div className="facility-grid">{[['⌖','Central location','Easy to find in the heart of Hosur.'],['▣','Hassle-free parking','Convenient parking right at the clinic.'],['◷','Open every day','Doctors available 9 AM to 7 PM.'],['↔','Pickup & drop-off','Support to make visits simpler.'],['♿','Wheelchair access','Care is accessible to everyone.']].map(([icon,title,text]) => <div key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
      <section className="section testimonials"><div className="container"><div className="section-head"><div><p className="eyebrow">WHAT OUR PATIENTS SAY</p><h2>Kind words, brighter smiles.</h2></div><div className="slider-controls"><button aria-label="Previous testimonial" onClick={() => setQuote((quote + testimonials.length - 1) % testimonials.length)}>←</button><button aria-label="Next testimonial" onClick={() => setQuote((quote + 1) % testimonials.length)}>→</button></div></div><div className="quote-wrap"><article className="quote active"><span>“</span><blockquote>{testimonials[quote][0]}</blockquote><p><b>{testimonials[quote][1]}</b><br/><small>{testimonials[quote][2]}</small></p></article></div></div></section>
      <section id="treatment-list" className="section full-list"><div className="container"><p className="eyebrow">COMPLETE CARE, ONE CLINIC</p><h2>Every smile has a solution.</h2><div className="pill-list">{['Dental implants','Laser dentistry','Root canal therapy','Wisdom tooth extraction','Dental bridges','Veneers','Pediatric dentistry','Flap surgery','Clear aligners'].map(x => <span key={x}>{x}</span>)}</div><button className="button" onClick={() => setAppointmentOpen(true)}>Talk to our team <span>→</span></button></div></section>
      <section id="faq" className="section faq"><div className="container faq-grid"><div><p className="eyebrow">COMMON QUESTIONS</p><h2>Answers for your peace of mind.</h2><p className="body-copy">Have a different question? Our friendly team is just a call away.</p><a href="tel:+919862890897" className="text-link">Call the clinic <span>↗</span></a></div><div className="accordion">{faqs.map(([q,a],i) => <details key={q} open={i===0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
      <section id="contact" className="section contact"><div className="container contact-grid"><div className="contact-copy"><p className="eyebrow">CONTACT US</p><h2>We would love<br/>to hear from you.</h2><p>Whether it is a first visit or a follow-up, let’s make your dental care feel simple.</p><div className="contact-info"><p><span>⌖</span><b>Visit us</b><br/>B2/8, SBM Layout, Anthivadi,<br/>Hosur, Tamil Nadu 635109</p><p><span>✉</span><b>Email us</b><br/><a href="mailto:info@sakthidentalclinic.in">info@sakthidentalclinic.in</a></p><p><span>⌕</span><b>Call us</b><br/><a href="tel:+919862890897">+91 9862890897</a> / <a href="tel:+919363298118">+91 9363298118</a></p></div></div><form noValidate onSubmit={submit}><label>Name <input name="name" required placeholder="Your full name"/></label><label>Email <input name="email" type="email" required placeholder="you@example.com"/></label><label>Phone number <input name="phone" required placeholder="Your phone number"/></label><label>Your message <textarea name="message" rows="4" placeholder="How can we help?"/></label><button className="button" type="submit">Submit <span>→</span></button><p className="form-status" aria-live="polite">{formMessage}</p></form></div></section>
      <section id="privacy" className="section privacy"><div className="container"><p className="eyebrow">PRIVACY POLICY</p><h2>Your information, handled with care.</h2><div className="privacy-grid"><p>We collect only the personal details you voluntarily provide through forms, such as your name, email address and phone number, to respond to enquiries and improve our service.</p><p>We do not sell, trade or rent personal information. We use appropriate safeguards to protect data and may use cookies to improve your experience.</p><p>Questions about privacy? Contact us at <a href="mailto:info@sakthidentalclinic.in">info@sakthidentalclinic.in</a>.</p></div></div></section>
    </main>
    <footer><div className="container footer-grid"><Brand /><div><h4>Navigate</h4>{nav.slice(0,4).map((x,i) => <a href={`#${anchors[i]}`} key={x}>{x}</a>)}</div><div><h4>Our services</h4>{['Teeth cleaning','Orthodontics','Dental implants','Pediatric care'].map(x => <a href="#treatments" key={x}>{x}</a>)}</div><div><h4>Follow along</h4><div className="social"><a href="#contact">ig</a><a href="#contact">f</a><a href="#contact">▶</a></div><p className="footer-phone">+91 98628 90897</p></div></div><div className="container subfooter"><span>© 2026 Sakthi Dental Clinic</span><a href="#privacy">Privacy policy</a><span>Made with care in Hosur</span></div></footer>
    {appointmentOpen && <div className="modal-backdrop" role="presentation"><div className="modal" role="dialog" aria-modal="true" aria-label="Book a visit"><button className="close" aria-label="Close" onClick={() => setAppointmentOpen(false)}>×</button><p className="eyebrow">BOOK A VISIT</p><h2>Let’s take care of your smile.</h2><p>Call us at <a href="tel:+919862890897">+91 98628 90897</a> or send your details through the contact form. Our team will help you find a convenient time.</p><button className="button" onClick={() => setAppointmentOpen(false)}>Got it <span>→</span></button></div></div>}
  </>;
}
